version: "3.8"

services:
  mysql:
    image: mysql:8.0.17
    platform: linux/amd64
    container_name: mysql
    # 접근 포트 (컨테이너 외부: 컨테이너 내부)
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_USER=tester # 새로운 사용
      - MYSQL_PASSWORD=tester1234 # 새로운 사용자의 비밀번호
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no

    volumes:
      # 설정 디렉토리 전체를 사용
      - ./docker-volumes/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      # 초기화 SQL 스크립트 위치
      - ./docker-volumes/mysql/init:/docker-entrypoint-initdb.d
      # 컨테이너의 데이터 로컬로 마운트
      - ./docker-volumes/mysql/data:/var/lib/mysql
    networks:
      - db_net
    restart: always

networks:
  db_net:
    driver: bridge
